### ISSUE TITLE
(Question - Minor) Framebuffer size optimization to output 720p ?

### ISSUE THREAD

**Issue by iyenal** [neagix/wii-linux-ngx#15]
Hello,

Can the framebuffer size be optimized to output to a higher resolution than native one, like reducing bit depth of colors to use less place and store more pixel data, and output more than usual/native 420p resolution ? I don't know exactly Wii framebuffer specification, but I think it's theorically possible.

Thanks in advance.

**Comment by neagix** [comment]
You could read the driver source code: https://github.com/neagix/wii-linux-ngx/blob/b645c8aa773d6e084ff0273b174b074004b634bc/drivers/video/gcnfb.c

I don't think it's possible, but if you find a way then you can post about it.
