### ISSUE TITLE
Modprobe: could not open moddep file

### ISSUE THREAD

**Issue by RattletraPM** [neagix/wii-linux-ngx#16]
Hello!

Sorry if this might not a proper issue but I couldn't find any answer on this GitHub page or any other Wii Linux related page. What I'm trying to do with my Wii is to connect and use another Wi-Fi USB interface other than the built-in one. The interface I have has an Atheros AR9271 chipset. So, according to Debian's documentation, I've added non-free to sources.list and then I've installed the correct firmware using

`apt-get install firmware-atheros`

The documentation says that the correct module should be loaded, but this is not happening. Running modinfo ath9k_htc returns "modinfo: ERROR: Module alias ath9k_htc not found." while modprobe ath9k_htc gives me this error:

`libkmod: ERROR ../libkmod/libkmod.c:557 kmod_search_moddep: could not open moddep file '/lib/modules/3.15.10ngx+/modules.dep.bin'`

I suppose then that the required modules for wii-linux-ngx are built in the init image and, if so, is there a way to load other firmware & modules via the OS itself? If not, is there a way do add your own while compiling the kernel?

Thanks in advance!

**Comment by neagix** [comment]
First you should check if that module is enabled in the kernel config; yes, you can always compile the kernel and any module from this repository.
