### ISSUE TITLE
Gumboot source code?

### ISSUE THREAD

**Issue by nicolascolla** [neagix/wii-linux-ngx#20]
Is the gumboot source available somewhere? Or is it closed-source?

**Comment by neagix** [comment]
It is closed source, I could look into releasing it but I did not see much interest back then when I announced it.

**Comment by nicolascolla** [comment]
@neagix I'm trying to develop a distro for all third-generation PowerPC devices, including Nintendo consoles, and, while this project is in an extremely early stage, the gumboot source code would be interesting to look at, if only to make slight aesthetic modifications to it.

**Comment by neagix** [comment]
@nicolascolla I would have to clear the permission from someone who helped me with some code back then.

Not sure it will get through; meanwhile you can look at https://github.com/lewurm/ppcskel
Story: there was a file http://bootmii-devel.googlegroups.com/web/ppcskel.zip which is no more available, so searching around for `ppcskel.zip` might get you that same source.

On top of that I updated the FAT driver, fixed some bugs and reorganised the code.

**Comment by loquesangra** [comment]
@neagix any news? I'm trying to get [Sabotage Linux](http://sabo.xyz) to work, and I want to build Gumboot from source. thanks

**Comment by neagix** [comment]
@loquesangra I have sent an email to one of the original authors, will post here when I get a reply.

In any case license would be GPL version 2

**Comment by neagix** [comment]
The source has been released: https://github.com/neagix/gumboot

It is GNU/GPL v2.
