### ISSUE TITLE
Booting ends up with a reset. Only the tux icon is showing up.

### ISSUE THREAD

**Issue by DerNuntius** [neagix/wii-linux-ngx#21]
Hi, I have a problem booting the kernel. I made the two partitions and extracted the bootmii and rootfs archive in the partitions. When I booted the Kernel Image the only thing I get is the image of tux. After 10 seconds there's a reset.

**Comment by mehlon** [comment]
I have this issue as well. Did you solve it?

**Comment by DerNuntius** [comment]
Yes, I had a corrupted rootfs partition.
