### ISSUE TITLE
Ability to run in background along with wii menu? Sniffing Bluetooth Handshake...

### ISSUE THREAD

**Issue by nathanRamaNoodles** [neagix/wii-linux-ngx#23]
I'm trying to sniff the Bluetooth pairing process using Linux in the Wii.  So far, I have wireshark running on the wii :) and it works fine...however, the Wii doesn't connect to my wiimote in bootmii.
Is there a way to sniff the bluetooth pairing/handshake while linux is running?

**Comment by neagix** [comment]
I doubt it, it's probably done in ARM9.
