### ISSUE TITLE
Undefined reference when trying to build kernel

### ISSUE THREAD

**Issue by ThatWeirdAndrew** [neagix/wii-linux-ngx#25]
I am trying to build the kernel from the experimental-v4.x branch. I am able to make wii_defconfig without errors. However, when I try to make the zImage with this command:
`make zImage -j4 ARCH=powerpc GCC_HOST=powerpc-linux-gnu- CROSS_COMPILE=powerpc-linux-gnu- CC="ccache powerpc-linux-gnu-gcc"`, I get the error:
```
arch/powerpc/kernel/built-in.o: In function `udbg_early_init':
(.init.text+0x1834): undefined reference to `udbg_init_usbgecko'
arch/powerpc/platforms/built-in.o: In function `wii_machine_kexec_prepare':
wii.c:(.text+0x574): undefined reference to `kimage_add_preserved_region'
Makefile:935: recipe for target 'vmlinux' failed
```
How can I solve this?

**Comment by neagix** [comment]
Sorry, it seems like you are having Linux kernel building issues which are not specific to this kernel fork.

Try to `clean` before building.

**Comment by ThatWeirdAndrew** [comment]
I tried running `make clean` before building and I get the same error.

**Comment by drewbug** [comment]
Grab the `wii-mini-mode_defconfig` from the stable branch, and unset `CONFIG_KEXEC`
