### ISSUE TITLE
Using other rootfs?

### ISSUE THREAD

**Issue by Phantop** [neagix/wii-linux-ngx#26]
I think it's safe to say that this project is somewhat dead, but the kernel this comes with is still functional and it's a bit interesting to try to use it.

As experimentation, I'm trying to get something newer than Debian Jessie to run. However, I have no clue what to do to the rootfs I downloaded (trying to use Adelie Linux since it supports PowerPC) to get it to work right. All I get is a Tux icon but not even any terminal output, and the only file I've been modifying in the rootfs is fstab to make it match up with the Wii.

So, how exactly does one put together a rootfs compatible with wii-linux-ngx and gumboot?

**Comment by neagix** [comment]
> I think it's safe to say that this project is somewhat dead

I am still maintaining it, but there are no new developments planned. There might be, they are just not planned nor to be expected.

> the only file I've been modifying in the rootfs is fstab to make it match up with the Wii.

I can only offer some advice about the official rootfs, you should start from that and **not** with a modified one.

**Comment by Phantop** [comment]
Can I then rephrase this slightly? Sorry if I came off as rude, but then what exactly is done to put together the official rootfs? I have been using it, but it being stuck on Jessie is somewhat a shame.

As a side note, trying to update using the Debian Ports Archive breaks WiFi functionality for me, even though it works prior to the update and works when using the standard Jessie archive.

**Comment by neagix** [comment]
@Phantop I had already tried using a more recent distro and it was a dead end; cannot remember precisely the reasons.
