### ISSUE TITLE
Is Ubuntu 12.04 supported?

### ISSUE THREAD

**Issue by ultra0000** [neagix/wii-linux-ngx#27]
I know this is a little bit old project, but does this support Ubuntu 12.04? i tried loading it, but it only gives me the linux penguin and it reboots

EDIT: i got it to load, the problem was, the linux partition was on ext4, so i installed Ubuntu 12.04 on QEMU and then mounted it, and then copied everything to a ext3 partition with the terminal. And then it loaded, saying "The system is running on low graphics mode" or something like that, then i press enter because there's no "OK" option, then a couple of options appear, but everyone just leaves you in a screen with a cursor, if i do Ctrl + Alt + F1 i get to the terminal, and if i do startx it gives me an error, if i do it with sudo (NOTE: i had to fix the sudo command from my laptop because it wasnt working) it gives me a mouse on screen and then it lags A LOT, and it gets stuck in there.

**Comment by MiniGamer2015** [comment]
I forgot to say, i used the "Ubuntu preinstalled desktop" thing that's on the ubuntu website.

**Comment by sardach** [comment]
What you're trying to achieve or run? If you want a graphic desktop environment, it will be hard. A light window manager can work (something like JWM)

**Comment by derek57** [comment]
Kernel 3.15.10 works up until the Ubuntu 17 Zesty PowerPC development branch, right before they decided to completely drop PPC32 bit support at all.

**Comment by neagix** [comment]
You can try, but the system has not a lot of memory. I would aim for something extremely lightweight.
