### ISSUE TITLE
Cant extract rootfs.tar.xz

### ISSUE THREAD

**Issue by NeunMuenze92001** [neagix/wii-linux-ngx#28]
Hi Everyone I have a Problem with the rootfs.tar.xz file I tried to extract it in my SD Card  in Windows I used 7zip Winrar and other Programms and they all give me Errors How do I Do this???

**Comment by ThatWeirdAndrew** [comment]
Try flashing the .img file instead

**Comment by sardach** [comment]
You can use dd for flash the SD
sudo umount /dev/mmcblk0pX
sudo dd if=/path/to/rootfs.tar.xz of=/dev/mmcblk0pX bs=4M && sync

Or try balenaEtcher for a GUI solution
