### ISSUE TITLE
Installation process?

### ISSUE THREAD

**Issue by Meganium97** [neagix/wii-linux-ngx#29]
Hey, I was just checking on how you would install this because for me it's not very clear on how to do it. Could anyone explain it to me?

**Comment by one-and-only** [comment]
Hi - It's super simple, actually. All you have to do is grab the latest release from this github repo, download the ```wii-jessie-sd.img.xz``` file, and then flash it onto an SD card through something like BalenaEtcher. After that, you can launch BootMii on your Homebrewed Wii, which will bring up Gumboot. Select the top option that says something about loading wii-ngx linux by cycling with the "Power" button on the Wii until that is highlighted and then long-pressing the "Reset" Wii button on the front and releasing. After that, it should say it is loading the Linux kernel ```/bootmii/zImage.ngx```. Give it some time. After loading, it will proceed to boot up Debian Jessie. For me, there are some issues with Graphics. It is a weird black and white color, and flashes on and off constantly. I don't know what is going on with that, but it still works. Hope this helped!

**Comment by neagix** [comment]
I have added a note in the README; feel free to make PRs to improve that.

**Comment by Greeg0** [comment]
> Hi - It's super simple, actually. All you have to do is grab the latest release from this github repo, download the `wii-jessie-sd.img.xz` file, and then flash it onto an SD card through something like BalenaEtcher. After that, you can launch BootMii on your Homebrewed Wii, which will bring up Gumboot. Select the top option that says something about loading wii-ngx linux by cycling with the "Power" button on the Wii until that is highlighted and then long-pressing the "Reset" Wii button on the front and releasing. After that, it should say it is loading the Linux kernel `/bootmii/zImage.ngx`. Give it some time. After loading, it will proceed to boot up Debian Jessie. For me, there are some issues with Graphics. It is a weird black and white color, and flashes on and off constantly. I don't know what is going on with that, but it still works. Hope this helped! I mainly use it through SSH, so it doesn't matter for me.

To solve the graphics issue, go into the GUMBOOT folder, and open gumboot.lst

There should be an option for the video mode and it is PAL60 by default.

Set it to NTSC if you are are in the Americas :)
