### ISSUE TITLE
No documentation about compiling this kernel.

### ISSUE THREAD

**Issue by KcrPL** [neagix/wii-linux-ngx#30]
Could anyone help me compile the experimental 4.X branch kernel?

Literally no idea, never compiled a kernel before and there is literally no documentation about it.

**Comment by loquesangra** [comment]
rtfm on a distro wiki or something

**Comment by loquesangra** [comment]
Ok, but for real @KcrPL it depends on how your distribution does it. I'm trying to get [Sabotage Linux](http://sabo.xyz), and I've written a recipe that has successfully built the kernel, although I haven't gotten it to boot through yet... So yeah, I'll upstream it when it works for me. I recommend you use Sabotage too. It's stable and cross compilation is very simple once you got it figured out. And it's especially lightweight !

**Comment by loquesangra** [comment]
So once I do it'll just be `butch install kernelwii`.

**Comment by neagix** [comment]
Please refer to kernel documentation.
