### ISSUE TITLE
Farter's patch breaks early console output

### ISSUE THREAD

**Issue by neagix** [neagix/wii-linux-ngx#4]
When using Farter's patch the Linux kernel boot logo is fine, but INIT text cannot be seen at all.

Only later on, when ttys are initialized, one can see the login prompt in the console.

I did not test this yet with `cnfb:nostalgic` option.

Cc @deltaresero

**Comment by neagix** [comment]
Can't reproduce this anymore; however, the situation where the boot logo only appears seems to happen sometimes. Will need more investigation if it's reproducible again.

**Comment by DeltaResero** [comment]
So far I haven't had this happen at all.

**Comment by loquesangra** [comment]
If it means anything @neagix , I'm having this issue right now. Although I'm also bootlooping even after [https://github.com/neagix/wii-linux-ngx/issues/17#issuecomment-487561729](scrapping the rvl-di string off). I can't use a serial USB connection to know what's going on and I'd like to see the initlog :S

**Comment by loquesangra** [comment]
My bad this should go in #8 instead <_<
